### ISSUE TITLE
Question: how do you actually use this?

### ISSUE THREAD

**Issue by ChemMitch** [hamsterbacke23/multicolumn-polyfill#8]
I see the script
 if (!Modernizr.csscolumns) {
   $('.mycolumn-element').multicolumn();
 }

but what do you put into your HTML so that columns actually appear?
A little example would be nice.

**Comment by hamsterbacke23** [comment]
Hi there, 

You only need this polyfill if you want to support IE9 or IE8!

A classic example would be an unordered list like this:

```
<ul class="mycolumn-element>
   <li>first element</li>
   <li>second element</li>
...
</ul>
```

Usually in modern browsers you can add CSS to make this list appear in multiple columns:

```
.mycolumn-element {
  column-count: 3;
}
```
See an [example here.](https://codepen.io/hamsterbacke82/pen/poeoBKB)

However, this will not work for IE9 and IE8 so you need this polyfill to make it work there as well!
